export interface ProductVariant {
  variantId: string;
  size?: string;
  color?: string;
  colorHex?: string;
  inStock: boolean;
}

export interface Product {
  sku: string;
  name: string;
  slug: string;
  description: string;
  price: number;
  category: string;
  image: string;
  zone: string;
  brand: string;
  type: "part" | "apparel";
  wholesalePrice?: number;
  specs?: Record<string, string>;
  compatibility?: string[];
  variants?: ProductVariant[];
}

// ─── Boatify Original Parts ──────────────────────────────────────
const boatifyParts: Product[] = [
  {
    sku: "BOA-1001",
    name: "LED Navigation Light Kit",
    slug: "led-navigation-light-kit",
    description: "USCG-approved LED navigation light set includes a combination red/green bow light and a white stern light. Designed for boats under 20 feet, these energy-efficient LEDs draw minimal power while providing 2-nautical-mile visibility. Includes stainless steel mounting hardware and weather-sealed wiring harnesses.",
    price: 42.99,
    category: "Lighting & Electrical",
    image: "/products/nav-lights.jpg",
    zone: "bow",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 30.09,
  },
  {
    sku: "BOA-1002",
    name: "Automatic Bilge Pump 1100 GPH",
    slug: "automatic-bilge-pump-1100-gph",
    description: "Submersible automatic bilge pump with built-in float switch activates when water levels rise, pumping up to 1,100 gallons per hour. Features a strainer base to prevent debris clogging and snap-lock design for easy maintenance. Draws only 3.0 amps at 12V and includes a 3/4-inch discharge port with check valve.",
    price: 34.99,
    category: "Plumbing & Pumps",
    image: "/products/bilge-pump.jpg",
    zone: "hull",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 24.49,
  },
  {
    sku: "BOA-1003",
    name: "Stainless Steel Pull-Up Cleat 6\" (2-Pack)",
    slug: "stainless-steel-pull-up-cleat-6-inch",
    description: "Heavy-duty 316 marine-grade stainless steel pop-up cleats that sit flush with the deck when not in use, eliminating trip hazards. Each cleat handles up to 2,000 lbs of load and springs back into the recessed position when released. Mounting hardware and backing plate template included for both units.",
    price: 48.95,
    category: "Deck Hardware",
    image: "/products/cleats.jpg",
    zone: "deck",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 34.27,
  },
  {
    sku: "BOA-1004",
    name: "Marine Fuel Line Assembly Kit",
    slug: "marine-fuel-line-assembly-kit",
    description: "Complete fuel line replacement kit includes 8 feet of EPA-compliant 3/8-inch fuel hose, a universal primer bulb, and quick-connect fittings for most outboard engines. All components are ethanol-resistant and rated for use with E10 fuel blends. Kit also includes hose clamps and a fuel demand valve.",
    price: 29.95,
    category: "Fuel Systems",
    image: "/products/fuel-line.jpg",
    zone: "stern",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 20.97,
  },
  {
    sku: "BOA-1005",
    name: "Rotary Steering Helm Kit with 14' Cable",
    slug: "rotary-steering-helm-kit",
    description: "Single-cable rotary steering system compatible with most outboard engines up to 150 HP, featuring smooth 3.5-turn lock-to-lock operation. Includes the helm unit, a 14-foot steering cable with stainless core, and a 13-inch three-spoke steering wheel with comfort grip. Bezel and dash mounting hardware included.",
    price: 189.99,
    category: "Steering & Controls",
    image: "/products/steering-helm.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 132.99,
  },
  {
    sku: "BOA-1006",
    name: "Pro Angler Bass Boat Seat with Pedestal",
    slug: "pro-angler-bass-boat-seat",
    description: "High-back folding fishing seat with marine-grade vinyl upholstery, molded foam padding, and an aluminum swivel frame. Pairs with the included 13-inch fixed-height anodized aluminum pedestal and 7x7 swivel base plate. The seat folds flat for storage and features a drainage channel to prevent water pooling.",
    price: 129.99,
    category: "Seating & Furniture",
    image: "/products/boat-seat.jpg",
    zone: "deck",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 90.99,
  },
  {
    sku: "BOA-1007",
    name: "Hydraulic Trim Tab Set 12x9\"",
    slug: "hydraulic-trim-tab-set",
    description: "Bolt-on stainless steel trim tab plates (12\" x 9\" per side) with hydraulic actuators for boats 15 to 20 feet in length. Improves planing speed, fuel efficiency, and ride stability in choppy conditions by adjusting running attitude. Includes dual-rocker switch helm control, hydraulic lines, and all mounting hardware.",
    price: 549.99,
    category: "Steering & Controls",
    image: "/products/trim-tabs.jpg",
    zone: "stern",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 384.99,
  },
  {
    sku: "BOA-1008",
    name: "4-Gauge Marine Instrument Panel",
    slug: "4-gauge-marine-instrument-panel",
    description: "Pre-wired four-gauge dashboard panel includes a speedometer (0-65 MPH), tachometer (0-7000 RPM), fuel level gauge, and voltmeter, all with white LED backlighting. Compatible with most outboard engines using standard sensor signals. Black-bezel gauges mount in a molded ABS panel that fits standard dash cutouts.",
    price: 219.95,
    category: "Gauges & Instruments",
    image: "/products/gauge-panel.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 153.97,
  },
  {
    sku: "BOA-1009",
    name: "Universal Trolling Motor Mount",
    slug: "universal-trolling-motor-mount",
    description: "Heavy-duty aluminum quick-release trolling motor mount designed for bow installation on bass boats and jon boats. Accommodates motors with shafts up to 62 inches and features a reinforced pivot pin with stainless steel locking mechanism. Powder-coated black finish resists corrosion in both fresh and brackish water.",
    price: 74.99,
    category: "Trolling Motors & Accessories",
    image: "/products/trolling-mount.jpg",
    zone: "bow",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 52.49,
  },
  {
    sku: "BOA-1010",
    name: "Recirculating Livewell Kit with Timer",
    slug: "recirculating-livewell-kit",
    description: "Complete livewell aeration system includes a 600 GPH recirculating pump, adjustable timer module (cycles every 2-15 minutes), spray bar aerator head, and all plumbing fittings. Keeps bait and tournament fish alive with oxygenated, circulated water. Fits standard livewells up to 30 gallons.",
    price: 64.95,
    category: "Plumbing & Pumps",
    image: "/products/livewell-kit.jpg",
    zone: "deck",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 45.47,
  },
  {
    sku: "BOA-1011",
    name: "Marine Bass Boat Carpet Kit (6' x 20')",
    slug: "marine-bass-boat-carpet-kit",
    description: "UV-stabilized polypropylene marine carpet in charcoal gray, cut to a standard 6-foot width with 20 linear feet per roll. Features a rubber-backed non-skid underside that bonds securely with marine carpet adhesive. Resists mold, mildew, and fading, and drains quickly after water exposure.",
    price: 159.99,
    category: "Flooring & Interior",
    image: "/products/carpet.jpg",
    zone: "deck",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 111.99,
  },
  {
    sku: "BOA-1012",
    name: "Pontoon Rail Fitting Square 1\" (4-Pack)",
    slug: "pontoon-rail-fitting-square",
    description: "Cast 316 stainless steel 90-degree rail fittings designed for 1-inch square pontoon railing. Set of four fittings allows rebuilding or extending fence sections on standard pontoon boats. Each fitting includes a set screw for secure attachment and polished finish to match existing hardware.",
    price: 36.99,
    category: "Deck Hardware",
    image: "/products/rail-fittings.jpg",
    zone: "rail",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 25.89,
  },
  {
    sku: "BOA-1013",
    name: "Ribbed Dock Fender 6.5x23\" (2-Pack)",
    slug: "ribbed-dock-fender",
    description: "Heavy-duty inflatable vinyl boat fenders with molded ribbing for maximum hull protection during docking and rafting. Each fender measures 6.5 inches in diameter by 23 inches long, sized for boats 20 to 30 feet. Includes two fender lines with pre-spliced eye loops and a needle valve inflation adapter.",
    price: 39.99,
    category: "Docking & Anchoring",
    image: "/products/fenders.jpg",
    zone: "hull",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 27.99,
  },
  {
    sku: "BOA-1014",
    name: "Fluke-Style Anchor 8 lb with Line Kit",
    slug: "fluke-style-anchor-kit",
    description: "Hot-dip galvanized fluke (Danforth-style) anchor rated for boats up to 24 feet, with excellent holding power in sand and mud bottoms. Kit includes the 8 lb anchor, 6 feet of 1/4-inch galvanized chain, and 100 feet of 3/8-inch three-strand nylon rode. A galvanized anchor shackle and thimble complete the setup.",
    price: 54.95,
    category: "Docking & Anchoring",
    image: "/products/anchor.jpg",
    zone: "bow",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 38.47,
  },
  {
    sku: "BOA-1015",
    name: "Dual-Bank Battery Switch with AFD",
    slug: "dual-bank-battery-switch",
    description: "Marine-grade rotary battery selector switch with four positions (Off/1/2/Both) and an integrated alternator field disconnect to protect the charging system. Rated for continuous 350-amp loads and 1,000-amp cranking, suitable for dual-battery bass boat setups. Rear-mount design with clearly labeled, color-coded terminal posts.",
    price: 44.99,
    category: "Lighting & Electrical",
    image: "/products/battery-switch.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 31.49,
  },
  {
    sku: "BOA-1016",
    name: "Dual USB Charger Socket 4.2A with Voltmeter",
    slug: "dual-usb-charger-socket",
    description: "Flush-mount 12V dual USB charging port delivers 4.2 amps total output for charging phones, fish finders, and tablets while on the water. Built-in blue LED voltmeter displays real-time battery voltage so you can monitor your electrical system at a glance. Fits a standard 1-1/8 inch dash or panel cutout.",
    price: 18.99,
    category: "Lighting & Electrical",
    image: "/products/usb-charger.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 13.29,
  },
  {
    sku: "BOA-1017",
    name: "RGB LED Boat Lighting Strip Kit (16')",
    slug: "rgb-led-boat-lighting-strip-kit",
    description: "Waterproof IP67-rated flexible LED strip with 300 SMD LEDs across 16 feet, controllable via wireless remote with 20 color options and multiple flash modes. Ideal for pontoon accent lighting, under-gunwale illumination, or livewell lighting on bass boats. Includes 12V inline power connector, adhesive backing, and mounting clips.",
    price: 37.95,
    category: "Lighting & Electrical",
    image: "/products/led-strip.jpg",
    zone: "hull",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 26.57,
  },
  {
    sku: "BOA-1018",
    name: "Stainless Steel LED Cup Holder (2-Pack)",
    slug: "stainless-steel-led-cup-holder",
    description: "Drop-in drink holders machined from 304 stainless steel with integrated blue LED accent rings powered by 12V connection. Each holder accommodates cans, bottles, and insulated tumblers up to 3.25 inches in diameter and features a 3/8-inch drain hole. Mounts flush in any flat surface with the included spade-bit template.",
    price: 28.99,
    category: "Deck Hardware",
    image: "/products/cup-holders.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 20.29,
  },
  {
    sku: "BOA-1019",
    name: "Flush-Mount Rod Holder 30\u00B0 (2-Pack)",
    slug: "flush-mount-rod-holder",
    description: "Polished 316 stainless steel flush-mount rod holders set at a 30-degree angle, ideal for trolling and transport rigging on bass boats and pontoons. Inner PVC liner protects rod blanks from metal contact, and a cap and lanyard keep each holder sealed when not in use. Standard 2-inch inner diameter fits most rod butts.",
    price: 33.99,
    category: "Fishing Accessories",
    image: "/products/rod-holders.jpg",
    zone: "rail",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 23.79,
  },
  {
    sku: "BOA-1020",
    name: "Marine Grab Handle 12\" Polished SS (2-Pack)",
    slug: "marine-grab-handle",
    description: "One-piece 316 stainless steel grab handles with concealed-screw flanges for a clean, snag-free installation on pontoon gates, bass boat consoles, or swim platforms. Each handle spans 12 inches with a 1-inch tubing diameter for a secure, comfortable grip even when wet. Set of two includes stainless mounting bolts, lock washers, and backing plates.",
    price: 39.95,
    category: "Deck Hardware",
    image: "/products/grab-handles.jpg",
    zone: "helm",
    brand: "Boatify",
    type: "part",
    wholesalePrice: 27.97,
  },
];

// ─── Bob's Machine Shop ──────────────────────────────────────────
const bobsMachineProducts: Product[] = [
  {
    sku: "BMS-001",
    name: "Action Series Hydraulic Jack Plate - 6\" Setback",
    slug: "bms-action-series-jack-plate-6",
    description: "Bob's Machine Shop's flagship hydraulic jack plate with the pump built directly into the structure — no separate pump, hoses, or transom-mounted components. Delivers 7.5\" total lift (1.5\" built-in plus 6\" adjustable travel) for outboards up to 300 HP / 625 lbs. Aircraft-grade aluminum construction with a limited lifetime structural warranty. Includes wiring harness, relays, and rocker switch. Made in Tampa, FL since 1978.",
    price: 1649.99,
    category: "Jack Plates",
    image: "/products/bms-action-jack-plate.jpg",
    zone: "stern",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Setback": "6\"",
      "HP Rating": "Up to 300 HP / 625 lbs",
      "Total Lift": "7.5\" (1.5\" built-in + 6\" travel)",
      "Weight": "~71 lbs",
      "Pump": "Built into plate (Action Series)",
      "Warranty": "Limited Lifetime Structure / 3-Year Pump",
      "Bolt Pattern": "Standard BIA",
      "Made In": "USA - Tampa, FL",
    },
  },
  {
    sku: "BMS-002",
    name: "Standard Series Hydraulic Jack Plate - 6\" Setback",
    slug: "bms-standard-series-jack-plate-6",
    description: "The original Bob's Machine hydraulic jack plate design — the lightest hydraulic plate on the market. Features a remote-mount pump housed inside the boat to reduce transom weight. Provides 7.5\" total lift for motors up to 300 HP. The 5-year pump warranty is the longest in the industry. Includes lift unit, controls, pump, switch, hoses, hydraulic oil, and instructions.",
    price: 1649.99,
    category: "Jack Plates",
    image: "/products/bms-standard-jack-plate.jpg",
    zone: "stern",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Setback": "6\"",
      "HP Rating": "Up to 300 HP / 625 lbs",
      "Total Lift": "7.5\" (1.5\" built-in + 6\" travel)",
      "Weight": "~70 lbs",
      "Pump": "Remote-mount (inside boat)",
      "Warranty": "Limited Lifetime Structure / 5-Year Pump",
      "Bolt Pattern": "Standard BIA",
      "Made In": "USA - Tampa, FL",
    },
  },
  {
    sku: "BMS-003",
    name: "Extreme Gen 3 Action Series Jack Plate - 6\" Setback",
    slug: "bms-extreme-gen3-jack-plate-6",
    description: "Built for the new generation of V8 and V10 outboards including Mercury Verado 400R and Yamaha 450. Handles motors up to 550 HP with the all-in-one Action Series pump design — no external hoses or transom-mounted components. Wider design accommodates Verado installations without spacers. At 66 lbs, it's lighter than the standard plates despite the higher HP rating.",
    price: 1999.99,
    category: "Jack Plates",
    image: "/products/bms-extreme-gen3-jack-plate.jpg",
    zone: "stern",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Setback": "6\"",
      "HP Rating": "Up to 550 HP",
      "Total Lift": "7.5\"",
      "Weight": "~66 lbs",
      "Pump": "Built into plate (Action Series)",
      "Warranty": "Limited Lifetime Structure / 3-Year Pump",
      "Bolt Pattern": "Standard BIA",
      "Fits": "Mercury V8/V10 Verado, Yamaha 450, etc.",
    },
  },
  {
    sku: "BMS-004",
    name: "Standard Versa Jac Manual Jack Plate - 6\" Setback",
    slug: "bms-versa-jac-manual-6",
    description: "Bob's budget-friendly manual jack plate crafted from aircraft-grade aluminum in a one-piece design (no setback spacers). Can be adjusted while the boat is in the water using the manual screw assembly. The real kicker: the manual assembly can be removed and swapped for a hydraulic cylinder kit to upgrade later. Fits outboards 35-300 HP.",
    price: 899.99,
    category: "Jack Plates",
    image: "/products/bms-versa-jac.jpg",
    zone: "stern",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Setback": "6\"",
      "HP Rating": "35 - 300 HP / 625 lbs",
      "Total Lift": "7.5\"",
      "Weight": "~45 lbs",
      "Type": "Manual (upgradeable to hydraulic)",
      "Warranty": "Limited Lifetime Structure",
      "Bolt Pattern": "Standard BIA",
      "Made In": "USA - Tampa, FL",
    },
  },
  {
    sku: "BMS-005",
    name: "Quick Slip Trolling Motor Connector",
    slug: "bms-quick-slip-connector",
    description: "Replaces the stock depth adjustment knob on your trolling motor with a lever-action quick-release connector. Allows fast, secure height adjustments with one hand — no more fumbling with the factory knob while fighting wind or current. Installs in about 60 seconds with no tools required. Available for Minn Kota (Maxxum, Fortrex, Terrova, Ultrex) and MotorGuide models.",
    price: 75.00,
    category: "Trolling Motors & Accessories",
    image: "/products/bms-quick-slip.jpg",
    zone: "bow",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Type": "Lever-action quick-release",
      "Compatibility": "Minn Kota & MotorGuide",
      "Install Time": "~60 seconds, no tools",
      "Weight": "1 lb",
      "Made In": "USA - Tampa, FL",
    },
    compatibility: ["Minn Kota Maxxum", "Minn Kota Fortrex", "Minn Kota Terrova", "Minn Kota Ultrex", "MotorGuide Gatormount"],
  },
  {
    sku: "BMS-006",
    name: "Balanced Trolling Motor Prop Nut",
    slug: "bms-balanced-prop-nut",
    description: "CNC-machined replacement propeller nut for trolling motors that allows tool-free propeller removal. Has 25%+ more mass than stock nuts, which reduces noise and vibrations for a smoother, quieter trolling motor operation. Precision-balanced design eliminates the wobble common with factory nuts.",
    price: 50.00,
    category: "Trolling Motors & Accessories",
    image: "/products/bms-balanced-prop-nut.jpg",
    zone: "bow",
    brand: "Bob's Machine Shop",
    type: "part",
    specs: {
      "Material": "CNC-machined aluminum",
      "Feature": "Tool-free prop removal",
      "Benefit": "25%+ more mass, reduced noise & vibration",
      "Made In": "USA - Tampa, FL",
    },
    compatibility: ["Minn Kota", "MotorGuide"],
  },
];

// ─── Transducer Shield & Saver ───────────────────────────────────
const transducerShieldProducts: Product[] = [
  {
    sku: "TSS-001",
    name: "TG-GT-6 Shield - Garmin GT22/GT24/GT52/GT54",
    slug: "tss-tg-gt-6-garmin-shield",
    description: "Aluminum alloy transducer shield with black powder coat finish designed to protect your Garmin GT22, GT24, GT52, and GT54 transducers from impact damage. Hydrodynamic profile cuts through water with minimal drag and won't interfere with sonar signal quality. Mounts on jack plates, hole shot plates, set backs, or trolling motors. Does NOT fit GT36 or GT56.",
    price: 109.95,
    category: "Transducer Protection",
    image: "/products/tss-garmin-shield.jpg",
    zone: "stern",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "Aluminum alloy, black powder coated",
      "Design": "Hydrodynamic - no signal interference",
      "Mount": "Jack plate, hole shot plate, set back, or trolling motor",
    },
    compatibility: ["Garmin GT22", "Garmin GT24", "Garmin GT52", "Garmin GT54"],
  },
  {
    sku: "TSS-002",
    name: "TS-DSS3-TS Shield - Lowrance Total Scan / Active Imaging",
    slug: "tss-lowrance-total-scan-shield",
    description: "Premium aluminum alloy shield built for Lowrance's larger scanning transducers including Total Scan, Structure Scan 3D, and the HDS Live Active Imaging 2-in-1 and 3-in-1 units. Protects your investment from stumps, rocks, and trailer bunks while maintaining full sonar performance. Black powder coat finish.",
    price: 189.00,
    category: "Transducer Protection",
    image: "/products/tss-lowrance-shield.jpg",
    zone: "stern",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "Aluminum alloy, black powder coated",
      "Design": "Hydrodynamic - no signal interference",
      "Mount": "Jack plate, hole shot plate, or set back",
    },
    compatibility: ["Lowrance Total Scan", "Lowrance Structure Scan 3D", "Lowrance Active Imaging 2-in-1", "Lowrance Active Imaging 3-in-1"],
  },
  {
    sku: "TSS-003",
    name: "TM-H8.3 Shield - Humminbird Mega SI",
    slug: "tss-humminbird-mega-si-shield",
    description: "Heavy-duty aluminum alloy shield designed specifically for Humminbird's Mega Side Imaging transducers including the Solix Mega G2N/G3N and Helix Mega G3N/G4N SI units. Protects the transducer from underwater hazards without compromising image quality. Black powder coat finish resists corrosion.",
    price: 179.00,
    category: "Transducer Protection",
    image: "/products/tss-humminbird-shield.jpg",
    zone: "stern",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "Aluminum alloy, black powder coated",
      "Design": "Hydrodynamic - no signal interference",
      "Mount": "Trolling motor, jack plate, or set back",
    },
    compatibility: ["Humminbird Solix Mega G2N SI", "Humminbird Solix Mega G3N SI", "Humminbird Helix Mega G3N SI", "Humminbird Helix Mega G4N SI"],
  },
  {
    sku: "TSS-004",
    name: "FFS BEAST - Forward Facing Sonar Mount",
    slug: "tss-ffs-beast-sonar-mount",
    description: "Premium CNC-machined rear transom mount for forward-facing sonar units including Garmin LiveScope (LVS32, LVS34, LVS62 XR) and Lowrance Active Target 1 & 2. 6061 aluminum alloy with black cerakote finish. Features an interlocking teeth design allowing 10-degree rotation increments and an integrated Spring Back Bracket that pivots up on submerged objects and snaps back automatically.",
    price: 399.00,
    category: "Transducer Protection",
    image: "/products/tss-ffs-beast.jpg",
    zone: "stern",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "6061 aluminum alloy, CNC-machined",
      "Finish": "Black cerakote",
      "Rotation": "10-degree increments (interlocking teeth)",
      "Feature": "Integrated Spring Back Bracket",
      "Mount": "Rear transom",
    },
    compatibility: ["Garmin LiveScope LVS32", "Garmin LiveScope LVS34", "Garmin LiveScope LVS62 XR", "Lowrance Active Target 1", "Lowrance Active Target 2"],
  },
  {
    sku: "TSS-005",
    name: "FFS ELITE - Trolling Motor Shaft FFS Mount",
    slug: "tss-ffs-elite-trolling-motor-mount",
    description: "Professional-grade trolling motor shaft mount for forward-facing sonar. CNC-machined from 6061 aluminum alloy with black cerakote finish. Interlocking teeth with 5-degree rotation increments for precise aiming. Adaptor head rotates between Forward/Down and Perspective/Scout modes. Fits all major trolling motor brands.",
    price: 299.00,
    category: "Transducer Protection",
    image: "/products/tss-ffs-elite.jpg",
    zone: "bow",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "6061 aluminum alloy, CNC-machined",
      "Finish": "Black cerakote",
      "Rotation": "5-degree increments (interlocking teeth)",
      "Modes": "Forward/Down and Perspective/Scout",
      "Mount": "Trolling motor shaft (universal)",
    },
    compatibility: ["Garmin LiveScope LVS32", "Garmin LiveScope LVS34", "Garmin LiveScope LVS62 XR", "Lowrance Active Target 1", "Lowrance Active Target 2"],
  },
  {
    sku: "TSS-006",
    name: "AP-GT-6 Armor Plate - Garmin GT22/GT24/GT52/GT54",
    slug: "tss-ap-gt-6-garmin-armor-plate",
    description: "Compact aluminum armor plate for Garmin GT22, GT24, GT52, and GT54 transducers mounted directly on the transom. A simpler, more affordable alternative to the full shield for boats that don't run a jack plate. Black powder coat finish. Bolt-on installation with included hardware.",
    price: 69.95,
    category: "Transducer Protection",
    image: "/products/tss-armor-plate.jpg",
    zone: "stern",
    brand: "Transducer Shield & Saver",
    type: "part",
    specs: {
      "Material": "Aluminum alloy, black powder coated",
      "Type": "Armor plate (transom mount)",
      "Design": "Compact, bolt-on",
    },
    compatibility: ["Garmin GT22", "Garmin GT24", "Garmin GT52", "Garmin GT54"],
  },
];

// ─── Pro Guide Batteries ─────────────────────────────────────────
const proGuideProducts: Product[] = [
  {
    sku: "PGB-001",
    name: "PGL24M100 - 12V 100Ah Deep Cycle LiFePO4",
    slug: "pro-guide-pgl24m100-12v-100ah",
    description: "Pro Guide's workhorse 12V deep-cycle lithium battery in a standard Group 24 footprint. At 23.8 lbs, it's less than half the weight of a comparable lead-acid battery while delivering 67% more usable energy. Built-in state-of-charge indicator and integrated BMS. Powers marine electronics, house loads, and fish finders all day long. 60-month free replacement warranty.",
    price: 699.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgl24m100.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Voltage": "12V",
      "Capacity": "100Ah / 1,280Wh",
      "Chemistry": "LiFePO4",
      "Group Size": "24",
      "Weight": "23.8 lbs",
      "Cycle Life": "3,000 cycles @ 80% DOD",
      "Charge Rate": "10A standard / 50A max",
      "Warranty": "60-month free replacement / 120-month pro-rata",
      "Features": "Built-in SOC indicator, integrated BMS",
    },
  },
  {
    sku: "PGB-002",
    name: "PGL24M100-ST - 12V 100Ah Starting LiFePO4",
    slug: "pro-guide-pgl24m100-st-starting",
    description: "A cranking/starting lithium battery designed to replace the lead-acid starting battery on outboard-powered bass boats. Provides 1,000 CCA equivalent while also serving as a deep-cycle battery for running 2-3 twelve-inch graphs and LiveScope simultaneously. The ProBoost feature provides emergency jump-start capability. Meets Mercury Marine lithium starting requirements.",
    price: 899.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgl24m100-st.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Voltage": "12V",
      "Capacity": "100Ah / 1,280Wh",
      "CCA": "1,000 PbEq",
      "Chemistry": "LiFePO4",
      "Group Size": "24",
      "Cycle Life": "3,000+ cycles @ 80% DOD",
      "Features": "ProBoost jump-start, brass dual terminals",
      "Warranty": "60-month free replacement / 120-month pro-rata",
    },
  },
  {
    sku: "PGB-003",
    name: "PGL31M180-DP - 12V 180Ah Dual Purpose LiFePO4",
    slug: "pro-guide-pgl31m180-dp-dual-purpose",
    description: "High-capacity dual-purpose battery that handles both starting and deep-cycle duties for demanding tournament fishing setups. The 200A BMS and Pro-Boost mode (which reserves 20% capacity for emergencies) ensure you're never stranded. IP67 waterproof, Bluetooth app monitoring, NMEA 2000 compatible, and built-in heating for cold-weather charging.",
    price: 1399.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgl31m180-dp.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Voltage": "12V",
      "Capacity": "180Ah / 2,304Wh",
      "CCA": "1,000 PbEq",
      "Chemistry": "LiFePO4",
      "Group Size": "31",
      "Weight": "41.89 lbs",
      "BMS": "200A",
      "Features": "IP67, Bluetooth, NMEA 2000, heating, Pro-Boost",
      "Warranty": "36-month free replacement / 120-month pro-rata",
    },
  },
  {
    sku: "PGB-004",
    name: "PGL36VM60 - 36V 60Ah Trolling Motor LiFePO4",
    slug: "pro-guide-pgl36vm60-36v-trolling",
    description: "Single-unit 36V battery that replaces three 12V batteries wired in series for your trolling motor. At 44 lbs, it saves massive weight compared to three lead-acid batteries (~180 lbs combined). The Pro-Boost mode reserves 10% capacity so you never get stranded. IP67 waterproof with Bluetooth monitoring and NMEA 2000 integration.",
    price: 1249.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgl36vm60.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Voltage": "36V",
      "Capacity": "60Ah / 2,304Wh",
      "Chemistry": "LiFePO4",
      "Group Size": "31",
      "Weight": "44.09 lbs",
      "BMS": "100A (heating enabled)",
      "Features": "IP67, Bluetooth, NMEA 2000, Pro-Boost",
      "Warranty": "60-month free replacement / 120-month pro-rata",
      "Fits": "Minn Kota Ultrex/Fortrex 36V, MotorGuide 36V",
    },
  },
  {
    sku: "PGB-005",
    name: "PGL36VM75 - 36V 75Ah Trolling Motor LiFePO4",
    slug: "pro-guide-pgl36vm75-36v-trolling",
    description: "The higher-capacity 36V option for tournament anglers who need maximum trolling motor runtime. 25% more amp hours than the 36VM60 in a Group 31 Tall case. Designed for heavy-duty marine applications where you need all-day power running spot-lock and navigating between spots. Built-in heating system allows cold-weather charging.",
    price: 1499.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgl36vm75.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Voltage": "36V",
      "Capacity": "75Ah / 2,880Wh",
      "Chemistry": "LiFePO4",
      "Group Size": "31 (Tall)",
      "Weight": "50.71 lbs",
      "BMS": "100A (heating enabled)",
      "Features": "IP67, Bluetooth, NMEA 2000, Pro-Boost, heating",
      "Warranty": "60-month free replacement / 120-month pro-rata",
    },
  },
  {
    sku: "PGB-006",
    name: "PGC-310 - 3-Bank 10A Onboard Charger",
    slug: "pro-guide-pgc-310-3-bank-charger",
    description: "The most popular charger for traditional 36V bass boat setups using three 12V batteries in series. Each of the 3 banks independently selects Lead Acid, AGM, or Lithium profiles — so you can charge mixed battery types simultaneously. IP68 submersible rated. Includes reverse polarity protection, thermal safeguards, and activation mode for dormant lithium batteries. Can stay plugged in year-round.",
    price: 309.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgc-310.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Banks": "3",
      "Output": "10A per bank (12V each)",
      "Chemistry Support": "Lead Acid, AGM, LiFePO4",
      "IP Rating": "IP68 (submersible)",
      "Input": "AC 110-120V, 60Hz",
      "Protection": "Reverse polarity, thermal, short circuit",
      "Warranty": "24-month free replacement / 48-month total",
    },
  },
  {
    sku: "PGB-007",
    name: "PGC-1236 - 12V + 36V 2-Bank Charger",
    slug: "pro-guide-pgc-1236-2-bank-charger",
    description: "The go-to charger for anglers running a single 36V lithium trolling motor battery alongside a 12V cranking/electronics battery. Two independent banks with full protection suite. The 12V bank supports selectable chemistry (lead-acid, AGM, or lithium) while the 36V bank is lithium-specific. Includes activation mode for waking dormant lithium batteries. IP68 rated.",
    price: 429.99,
    category: "Batteries & Power",
    image: "/products/pgb-pgc-1236.jpg",
    zone: "hull",
    brand: "Pro Guide Batteries",
    type: "part",
    specs: {
      "Banks": "2 (1x 12V + 1x 36V)",
      "Output": "10A per bank",
      "12V Bank": "Lead Acid / AGM / LiFePO4",
      "36V Bank": "LiFePO4 only",
      "IP Rating": "IP68 (submersible)",
      "Weight": "17.9 lbs",
      "Protection": "Over-voltage, over-current, short circuit, reverse polarity, thermal",
      "Warranty": "24-month free replacement / 48-month total",
    },
  },
];

// ─── Boatify Apparel ─────────────────────────────────────────────
const boatifyApparel: Product[] = [
  {
    sku: "APP-001",
    name: "Boatify Logo Snapback Hat",
    slug: "boatify-logo-snapback-hat",
    description: "Classic structured snapback hat with embroidered Boatify wave logo on the front and \"Boats Without Woes\" tagline on the side. Adjustable snap closure fits most sizes. Durable cotton twill construction built to handle life on and off the water.",
    price: 29.99,
    category: "Apparel",
    image: "/products/boatify-snapback.jpg",
    zone: "n/a",
    brand: "Boatify",
    type: "apparel",
    variants: [
      { variantId: "APP-001-NAV", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-001-CHR", color: "Charcoal", colorHex: "#4a4a4a", inStock: true },
      { variantId: "APP-001-WHT", color: "White", colorHex: "#ffffff", inStock: true },
    ],
  },
  {
    sku: "APP-002",
    name: "\"Boats Without Woes\" Trucker Hat",
    slug: "boats-without-woes-trucker-hat",
    description: "Richardson-style trucker hat featuring the \"Boats Without Woes\" tagline in bold embroidery across the front. Mesh back panels keep you cool on hot days on the water. Adjustable snapback closure.",
    price: 32.99,
    category: "Apparel",
    image: "/products/boatify-trucker.jpg",
    zone: "n/a",
    brand: "Boatify",
    type: "apparel",
    variants: [
      { variantId: "APP-002-NW", color: "Navy/White", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-002-BW", color: "Black/White", colorHex: "#1a1a1a", inStock: true },
      { variantId: "APP-002-CW", color: "Camo/White", colorHex: "#5c6b3c", inStock: true },
    ],
  },
  {
    sku: "APP-003",
    name: "Boatify Logo T-Shirt",
    slug: "boatify-logo-tshirt",
    description: "Soft ring-spun cotton tee with the Boatify wave logo front and center. Relaxed fit for all-day comfort whether you're on the boat or at the ramp. Pre-shrunk fabric holds up wash after wash.",
    price: 24.99,
    category: "Apparel",
    image: "/products/boatify-tshirt.jpg",
    zone: "n/a",
    brand: "Boatify",
    type: "apparel",
    variants: [
      { variantId: "APP-003-NAV-S", size: "S", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-NAV-M", size: "M", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-NAV-L", size: "L", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-NAV-XL", size: "XL", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-NAV-2X", size: "2XL", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-NAV-3X", size: "3XL", color: "Navy", colorHex: "#1e3a5f", inStock: true },
      { variantId: "APP-003-GRY-S", size: "S", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-GRY-M", size: "M", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-GRY-L", size: "L", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-GRY-XL", size: "XL", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-GRY-2X", size: "2XL", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-GRY-3X", size: "3XL", color: "Heather Gray", colorHex: "#b0b0b0", inStock: true },
      { variantId: "APP-003-WHT-S", size: "S", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-003-WHT-M", size: "M", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-003-WHT-L", size: "L", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-003-WHT-XL", size: "XL", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-003-WHT-2X", size: "2XL", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-003-WHT-3X", size: "3XL", color: "White", colorHex: "#ffffff", inStock: true },
    ],
  },
  {
    sku: "APP-004",
    name: "Boatify Performance Fishing Shirt",
    slug: "boatify-performance-fishing-shirt",
    description: "Lightweight moisture-wicking performance shirt with UPF 50+ sun protection. Features the Boatify wave logo on the left chest and \"Boats Without Woes\" across the upper back. Raglan sleeves allow full range of motion for casting. Quick-dry fabric keeps you comfortable all day on the water.",
    price: 44.99,
    category: "Apparel",
    image: "/products/boatify-performance-shirt.jpg",
    zone: "n/a",
    brand: "Boatify",
    type: "apparel",
    variants: [
      { variantId: "APP-004-WHT-S", size: "S", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-WHT-M", size: "M", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-WHT-L", size: "L", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-WHT-XL", size: "XL", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-WHT-2X", size: "2XL", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-WHT-3X", size: "3XL", color: "White", colorHex: "#ffffff", inStock: true },
      { variantId: "APP-004-BLU-S", size: "S", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-BLU-M", size: "M", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-BLU-L", size: "L", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-BLU-XL", size: "XL", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-BLU-2X", size: "2XL", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-BLU-3X", size: "3XL", color: "Light Blue", colorHex: "#a8d4e6", inStock: true },
      { variantId: "APP-004-SEA-S", size: "S", color: "Seafoam", colorHex: "#93e9be", inStock: true },
      { variantId: "APP-004-SEA-M", size: "M", color: "Seafoam", colorHex: "#93e9be", inStock: true },
      { variantId: "APP-004-SEA-L", size: "L", color: "Seafoam", colorHex: "#93e9be", inStock: true },
      { variantId: "APP-004-SEA-XL", size: "XL", color: "Seafoam", colorHex: "#93e9be", inStock: true },
      { variantId: "APP-004-SEA-2X", size: "2XL", color: "Seafoam", colorHex: "#93e9be", inStock: true },
      { variantId: "APP-004-SEA-3X", size: "3XL", color: "Seafoam", colorHex: "#93e9be", inStock: true },
    ],
  },
];

// ─── Combined Product List ───────────────────────────────────────
export const products: Product[] = [
  ...boatifyParts,
  ...bobsMachineProducts,
  ...transducerShieldProducts,
  ...proGuideProducts,
  ...boatifyApparel,
];

export const categories = [...new Set(products.map((p) => p.category))];
export const brands = [...new Set(products.map((p) => p.brand))];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string) {
  return products.filter((p) => p.category === category);
}

export function getProductsByBrand(brand: string) {
  return products.filter((p) => p.brand === brand);
}

export function getProductsByType(type: "part" | "apparel") {
  return products.filter((p) => p.type === type);
}
